import type { Place } from "./store";

const art = (title: string, from: string, to: string, icon: string) =>
  `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 800" fill="none">
      <defs>
        <linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0%" stop-color="${from}" />
          <stop offset="100%" stop-color="${to}" />
        </linearGradient>
      </defs>
      <rect width="1200" height="800" rx="56" fill="url(#g)"/>
      <circle cx="970" cy="150" r="170" fill="rgba(255,255,255,0.1)"/>
      <circle cx="170" cy="620" r="140" fill="rgba(255,255,255,0.12)"/>
      <text x="88" y="170" fill="white" font-size="72" font-family="Arial, Helvetica, sans-serif" opacity="0.95">${icon}</text>
      <text x="88" y="380" fill="white" font-size="62" font-family="Arial, Helvetica, sans-serif" font-weight="700">${title}</text>
      <text x="88" y="450" fill="rgba(255,255,255,0.88)" font-size="28" font-family="Arial, Helvetica, sans-serif">Warung by Feeling</text>
    </svg>
  `)}`;

export const seedPlaces: Place[] = [
  {
    id: "bubur-ayam-barito",
    name: "Bubur Ayam Barito",
    description: "Bubur lembut dengan topping ayam suwir, cakwe, dan sambal yang bisa diatur levelnya. Cocok buat pagi yang masih ngantuk.",
    tags: ["sarapan", "nasi", "ayam", "pedas"],
    address: "Jl. Barito II No.5, Kramat Pela, Kebayoran Baru, Jakarta Selatan",
    lat: -6.2446,
    lng: 106.8008,
    priceRange: 2,
    rating: 5,
    imageUrl: art("Bubur Ayam Barito", "#7c2d12", "#f97316", "🥣"),
    submittedBy: "Tim Warung",
    createdAt: "2026-04-29T06:20:00.000Z",
  },
  {
    id: "nasi-uduk-gondangdia",
    name: "Nasi Uduk Gondangdia",
    description: "Nasi uduk harum dengan tempe orek, telur, bihun, dan sambal kacang yang bikin porsi terasa rame.",
    tags: ["nasi", "gorengan", "ayam", "sarapan"],
    address: "Jl. Kendal No.1, Menteng, Jakarta Pusat",
    lat: -6.1854,
    lng: 106.8311,
    priceRange: 2,
    rating: 5,
    imageUrl: art("Nasi Uduk Gondangdia", "#92400e", "#fb923c", "🍚"),
    submittedBy: "Warga Menteng",
    createdAt: "2026-04-28T05:40:00.000Z",
  },
  {
    id: "sate-taichan-senayan",
    name: "Sate Taichan Senayan",
    description: "Sate taichan putih polos yang justru galak di sambal. Enak buat yang suka pedas tanpa basa-basi.",
    tags: ["sate", "pedas", "malam", "nasi"],
    address: "Sekitar Jl. Asia Afrika, Senayan, Jakarta Pusat",
    lat: -6.2276,
    lng: 106.799,
    priceRange: 3,
    rating: 4,
    imageUrl: art("Sate Taichan", "#7f1d1d", "#fb7185", "🍢"),
    submittedBy: "Anak nongkrong",
    createdAt: "2026-04-27T17:15:00.000Z",
  },
  {
    id: "kopi-tuku-cipete",
    name: "Kopi Tuku Cipete",
    description: "Kopi susu favorit banyak orang, manisnya pas, aromanya lembut, dan enak buat nemenin ngobrol lama.",
    tags: ["kopi", "manis", "jajanan"],
    address: "Jl. Cipete Raya No.7, Cipete Selatan, Jakarta Selatan",
    lat: -6.2779,
    lng: 106.7957,
    priceRange: 3,
    rating: 5,
    imageUrl: art("Kopi Tuku Cipete", "#3f1d0e", "#d97706", "☕"),
    submittedBy: "Kopi Hunter",
    createdAt: "2026-04-26T08:00:00.000Z",
  },
  {
    id: "bakso-akiaw-99-mangga-besar",
    name: "Bakso Akiaw 99 Mangga Besar",
    description: "Bakso dengan kuah gurih dan pilihan isian yang rame. Paling pas kalau lagi cari comfort food malam-malam.",
    tags: ["bakso", "malam", "mie", "nasi"],
    address: "Jl. Mangga Besar Raya, Taman Sari, Jakarta Barat",
    lat: -6.1437,
    lng: 106.8187,
    priceRange: 3,
    rating: 4,
    imageUrl: art("Bakso Akiaw 99", "#4c1d95", "#fb923c", "🧆"),
    submittedBy: "Bola kuah fanclub",
    createdAt: "2026-04-25T19:35:00.000Z",
  },
  {
    id: "mie-ayam-gondangdia",
    name: "Mie Ayam Gondangdia",
    description: "Mie ayam dengan topping melimpah, tekstur mie kenyal, dan pangsit yang bikin porsi berasa lengkap.",
    tags: ["mie", "ayam", "sarapan", "nasi"],
    address: "Jl. Gondangdia Dalam, Menteng, Jakarta Pusat",
    lat: -6.1848,
    lng: 106.8318,
    priceRange: 2,
    rating: 4,
    imageUrl: art("Mie Ayam Gondangdia", "#78350f", "#f59e0b", "🍜"),
    submittedBy: "Mie-mie club",
    createdAt: "2026-04-24T09:10:00.000Z",
  },
  {
    id: "martabak-pecenongan-65a",
    name: "Martabak Pecenongan 65A",
    description: "Martabak manis setebal hati mantan, topping cokelat kacang melimpah, cocok buat sharing atau ngibrit sendirian.",
    tags: ["martabak", "manis", "jajanan", "malam"],
    address: "Jl. Pecenongan No.65A, Gambir, Jakarta Pusat",
    lat: -6.1615,
    lng: 106.8238,
    priceRange: 4,
    rating: 5,
    imageUrl: art("Martabak Pecenongan", "#431407", "#f97316", "🥞"),
    submittedBy: "Tim lembur",
    createdAt: "2026-04-23T20:45:00.000Z",
  },
  {
    id: "soto-betawi-haji-husein",
    name: "Soto Betawi Haji Husein",
    description: "Soto Betawi kuah santan yang gurih dengan potongan daging lembut dan aroma rempah yang hangat.",
    tags: ["soto", "nasi", "ayam", "sarapan"],
    address: "Jl. Kramat Raya, Senen, Jakarta Pusat",
    lat: -6.1951,
    lng: 106.8398,
    priceRange: 3,
    rating: 5,
    imageUrl: art("Soto Betawi", "#854d0e", "#fbbf24", "🍲"),
    submittedBy: "Pecinta kuah",
    createdAt: "2026-04-22T11:00:00.000Z",
  },
  {
    id: "seafood-68-santa",
    name: "Seafood 68 Santa",
    description: "Tenda seafood ramai yang suka rame-rame. Udang, cumi, dan kepitingnya masuk ke mode pesta.",
    tags: ["seafood", "pedas", "malam", "nasi"],
    address: "Jl. Senopati, Kebayoran Baru, Jakarta Selatan",
    lat: -6.2431,
    lng: 106.8001,
    priceRange: 4,
    rating: 4,
    imageUrl: art("Seafood 68 Santa", "#164e63", "#06b6d4", "🦐"),
    submittedBy: "Nongkrong crew",
    createdAt: "2026-04-21T18:25:00.000Z",
  },
  {
    id: "nasi-goreng-kambing-kebon-sirih",
    name: "Nasi Goreng Kambing Kebon Sirih",
    description: "Nasi goreng kambing dengan aroma rempah tajam, porsi mantap, dan cocok buat makan tengah malam.",
    tags: ["nasi", "malam", "pedas", "ayam"],
    address: "Jl. Kebon Sirih, Menteng, Jakarta Pusat",
    lat: -6.1805,
    lng: 106.829,
    priceRange: 3,
    rating: 5,
    imageUrl: art("Nasi Goreng Kambing", "#422006", "#f59e0b", "🍚"),
    submittedBy: "Tim begadang",
    createdAt: "2026-04-20T21:10:00.000Z",
  },
  {
    id: "roti-bakar-eddy-cikini",
    name: "Roti Bakar Eddy Cikini",
    description: "Roti bakar klasik yang manis, hangat, dan gampang jadi alasan buat nongkrong lebih lama.",
    tags: ["manis", "jajanan", "kopi", "malam"],
    address: "Jl. Cikini Raya No.2, Menteng, Jakarta Pusat",
    lat: -6.191,
    lng: 106.8372,
    priceRange: 2,
    rating: 4,
    imageUrl: art("Roti Bakar Eddy", "#7c2d12", "#fb923c", "🍞"),
    submittedBy: "Teman ngopi",
    createdAt: "2026-04-19T19:20:00.000Z",
  },
  {
    id: "warteg-warmo-tebet",
    name: "Warteg Warmo Tebet",
    description: "Warteg lengkap dengan lauk melimpah, sambal yang nendang, dan harga yang bikin hati adem.",
    tags: ["nasi", "ayam", "gorengan", "pedas"],
    address: "Jl. Tebet Barat Dalam, Tebet, Jakarta Selatan",
    lat: -6.231,
    lng: 106.8566,
    priceRange: 2,
    rating: 5,
    imageUrl: art("Warteg Warmo", "#57534e", "#f97316", "🍛"),
    submittedBy: "Anak kos",
    createdAt: "2026-04-18T13:55:00.000Z",
  },
  {
    id: "ayam-geprek-bensu-rawamangun",
    name: "Ayam Geprek Bensu Rawamangun",
    description: "Ayam geprek crispy dengan sambal yang bisa bikin diam sejenak. Pas buat yang lagi butuh ledakan rasa.",
    tags: ["ayam", "pedas", "nasi", "malam"],
    address: "Jl. Pemuda, Rawamangun, Jakarta Timur",
    lat: -6.1967,
    lng: 106.8822,
    priceRange: 3,
    rating: 4,
    imageUrl: art("Ayam Geprek", "#881337", "#f43f5e", "🍗"),
    submittedBy: "Level sambal tinggi",
    createdAt: "2026-04-17T12:30:00.000Z",
  },
  {
    id: "sate-padang-ajo-ramon-blok-m",
    name: "Sate Padang Ajo Ramon Blok M",
    description: "Sate Padang kuah kental dengan bumbu kuning yang khas. Wajib dicocol sambil santai.",
    tags: ["sate", "pedas", "nasi", "malam"],
    address: "Area Blok M, Kebayoran Baru, Jakarta Selatan",
    lat: -6.2448,
    lng: 106.7999,
    priceRange: 3,
    rating: 5,
    imageUrl: art("Sate Padang", "#78350f", "#f59e0b", "🍢"),
    submittedBy: "Padang lovers",
    createdAt: "2026-04-16T18:05:00.000Z",
  },
  {
    id: "gorengan-pak-jaya-benhil",
    name: "Gorengan Pak Jaya Benhil",
    description: "Gorengan hangat yang baru naik dari wajan: tahu isi, bakwan, pisang goreng, semua ikut antre.",
    tags: ["gorengan", "jajanan", "sarapan", "malam"],
    address: "Jl. Bendungan Hilir, Tanah Abang, Jakarta Pusat",
    lat: -6.2085,
    lng: 106.818,
    priceRange: 1,
    rating: 4,
    imageUrl: art("Gorengan Pak Jaya", "#92400e", "#fde68a", "🍘"),
    submittedBy: "Kriuk collector",
    createdAt: "2026-04-15T16:50:00.000Z",
  },
];

export const seedVotes: Record<string, number> = {
  "bubur-ayam-barito": 148,
  "nasi-uduk-gondangdia": 132,
  "sate-taichan-senayan": 121,
  "kopi-tuku-cipete": 180,
  "bakso-akiaw-99-mangga-besar": 96,
  "mie-ayam-gondangdia": 87,
  "martabak-pecenongan-65a": 110,
  "soto-betawi-haji-husein": 124,
  "seafood-68-santa": 69,
  "nasi-goreng-kambing-kebon-sirih": 143,
  "roti-bakar-eddy-cikini": 75,
  "warteg-warmo-tebet": 101,
  "ayam-geprek-bensu-rawamangun": 88,
  "sate-padang-ajo-ramon-blok-m": 115,
  "gorengan-pak-jaya-benhil": 54,
};
