"use client";

import type { FormEvent, ReactNode } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowRight, BedDouble, CookingPot, Sofa, Sparkles, WandSparkles } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useDesignStore } from '@/lib/store';

const roomTypes = ['Kamar Tidur', 'Ruang Tamu', 'Dapur Mini', 'Kamar Mandi', 'Area Kerja'] as const;
const dimensions = ['3x3', '3x4', '4x4', 'custom'] as const;
const styles = ['Minimalis', 'Japandi', 'Industrial', 'Skandinavia', 'Bohemian', 'Modern'] as const;
const colors = ['Netral hangat', 'Putih bersih', 'Kayu alami', 'Abu gelap', 'Pastel lembut', 'Hitam elegan'] as const;

const iconByRoom: Record<string, ReactNode> = {
  'Kamar Tidur': <BedDouble size={16} />,
  'Ruang Tamu': <Sofa size={16} />,
  'Dapur Mini': <CookingPot size={16} />,
  'Kamar Mandi': <Sparkles size={16} />,
  'Area Kerja': <WandSparkles size={16} />,
};

const formatter = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 });

export default function HomePage() {
  const router = useRouter();
  const designs = useDesignStore((state) => state.designs);
  const [roomType, setRoomType] = useState<(typeof roomTypes)[number]>('Kamar Tidur');
  const [dimension, setDimension] = useState<(typeof dimensions)[number]>('3x3');
  const [style, setStyle] = useState<(typeof styles)[number]>('Japandi');
  const [color, setColor] = useState<(typeof colors)[number]>('Netral hangat');
  const [customSize, setCustomSize] = useState('');

  const stats = useMemo(
    () => [
      { value: '4', label: 'desain seed siap pakai' },
      { value: '8', label: 'inspirasi ruang kecil' },
      { value: '100%', label: 'fokus hemat tempat' },
    ],
    [],
  );

  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const params = new URLSearchParams({
      roomType,
      dimensions: dimension === 'custom' ? customSize || 'custom' : dimension,
      style,
      color,
    });
    router.push(`/generate?${params.toString()}`);
  };

  return (
    <main>
      <section className="hero shell">
        <div className="hero-grid">
          <div className="panel hero-copy">
            <span className="kicker">AI interior design untuk kos dan ruang mungil</span>
            <h1 className="h1">Ubah ruang kecil jadi terlihat rapi, lega, dan siap dipakai tiap hari.</h1>
            <p className="lead">
              KOST.AI membantu kamu mengubah ukuran kamar, preferensi warna, dan gaya favorit menjadi konsep desain yang
              praktis. Cocok untuk kamar kos, ruang tamu mini, dapur mungil, sampai area kerja 2x2.
            </p>
            <div className="hero-stats">
              {stats.map((stat) => (
                <div key={stat.label} className="stat">
                  <strong>{stat.value}</strong>
                  <span>{stat.label}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="panel visual-card">
            <div className="row" style={{ marginBottom: 18 }}>
              <span className="badge">
                <Sparkles size={15} />
                Live generator preview
              </span>
              <span className="tag">Purple creative mode</span>
            </div>
            <div className="room-mock" style={{ minHeight: 290 }}>
              <div className="room-grid" />
              <div className="room-layer" style={{ inset: '14% 58% 48% 10%', background: 'linear-gradient(180deg, rgba(139,92,246,.42), rgba(139,92,246,.08))' }} />
              <div className="room-layer" style={{ inset: '24% 18% 18% 52%', background: 'linear-gradient(180deg, rgba(255,255,255,.11), rgba(255,255,255,.04))' }} />
              <div className="room-layer" style={{ inset: '60% 16% 12% 16%', background: 'linear-gradient(180deg, rgba(192,132,252,.24), rgba(192,132,252,.08))' }} />
              <div style={{ position: 'absolute', left: 22, right: 22, bottom: 22, display: 'flex', justifyContent: 'space-between', alignItems: 'end', gap: 14 }}>
                <div>
                  <div className="tag" style={{ marginBottom: 10 }}>Generated by AI</div>
                  <h3 style={{ margin: 0, fontSize: 26 }}>Ruang compact, layout maksimal.</h3>
                  <p className="muted" style={{ margin: '8px 0 0', maxWidth: 330 }}>
                    Visual mockup CSS, rekomendasi produk, dan arahan style untuk ruang kecil.
                  </p>
                </div>
                <div className="panel-soft" style={{ padding: 14, minWidth: 150 }}>
                  <div style={{ fontSize: 12, color: '#c4b5fd', marginBottom: 6 }}>Area kerja</div>
                  <div style={{ fontWeight: 700 }}>Meja lipat + lampu ambient</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="section shell">
        <div className="section-head">
          <div>
            <h2>Generator desain</h2>
            <p>Isi preferensi ruang, lalu KOST.AI akan membuat draft desain yang lebih hemat tempat.</p>
          </div>
          <span className="tag">Indonesian UX</span>
        </div>

        <div className="panel" style={{ padding: 22 }}>
          <form onSubmit={submit} className="timeline" style={{ gap: 18 }}>
            <div className="form-grid">
              <div>
                <label className="field-label">Room type</label>
                <div className="option-group">
                  {roomTypes.map((item) => (
                    <label key={item} className="option-chip">
                      <input type="radio" name="roomType" checked={roomType === item} onChange={() => setRoomType(item)} />
                      <span>{iconByRoom[item]} {item}</span>
                    </label>
                  ))}
                </div>
              </div>

              <div>
                <label className="field-label">Preferensi warna</label>
                <select className="select" value={color} onChange={(event) => setColor(event.target.value as (typeof colors)[number])}>
                  {colors.map((item) => (
                    <option key={item} value={item}>
                      {item}
                    </option>
                  ))}
                </select>
              </div>
            </div>

            <div className="form-grid">
              <div>
                <label className="field-label">Ukuran ruangan</label>
                <div className="option-group">
                  {dimensions.map((item) => (
                    <label key={item} className="option-chip">
                      <input type="radio" name="dimension" checked={dimension === item} onChange={() => setDimension(item)} />
                      <span>{item === 'custom' ? 'custom' : `${item} m`}</span>
                    </label>
                  ))}
                </div>
                {dimension === 'custom' ? (
                  <div style={{ marginTop: 12 }}>
                    <input
                      className="input"
                      value={customSize}
                      onChange={(event) => setCustomSize(event.target.value)}
                      placeholder="Contoh: 2.5x3.2 m"
                    />
                  </div>
                ) : null}
              </div>

              <div>
                <label className="field-label">Style desain</label>
                <div className="option-group">
                  {styles.map((item) => (
                    <label key={item} className="option-chip">
                      <input type="radio" name="style" checked={style === item} onChange={() => setStyle(item)} />
                      <span>{item}</span>
                    </label>
                  ))}
                </div>
              </div>
            </div>

            <div className="button-row" style={{ justifyContent: 'space-between', alignItems: 'center' }}>
              <div className="muted">
                Preview: {roomType} • {dimension === 'custom' ? customSize || 'custom' : `${dimension} m`} • {style} • {color}
              </div>
              <button className="button" type="submit">
                Generate Desain
                <ArrowRight size={18} />
              </button>
            </div>
          </form>
        </div>
      </section>

      <section className="section shell">
        <div className="section-head">
          <div>
            <h2>Previously generated designs</h2>
            <p>Koleksi awal yang bisa langsung kamu buka, bandingkan, dan jadikan referensi belanja.</p>
          </div>
          <Link href="/inspirasi" className="pill">
            Lihat semua inspirasi
            <ArrowRight size={14} />
          </Link>
        </div>

        <div className="grid-3">
          {designs.map((design) => (
            <article className="card" key={design.id}>
              <div className="thumb">
                <img src={design.imageUrl} alt={`${design.roomType} ${design.style}`} />
              </div>
              <div className="card-body">
                <div className="row" style={{ marginBottom: 10 }}>
                  <div className="pills">
                    <span className="tag">{design.roomType}</span>
                    <span className="tag">{design.style}</span>
                  </div>
                  <span className="muted" style={{ fontSize: 13 }}>{design.dimensions}</span>
                </div>
                <h3 className="card-title">{design.roomType} {design.style}</h3>
                <p className="card-copy">{design.prompt}</p>
                <div className="button-row" style={{ marginTop: 16 }}>
                  <Link href={`/design/${design.id}`} className="button button-ghost">
                    Buka desain
                  </Link>
                  <span className="pill">{formatter.format(design.products.reduce((sum, product) => sum + product.price, 0))}</span>
                </div>
              </div>
            </article>
          ))}
        </div>
      </section>
    </main>
  );
}
